
part1: part1.c
	gcc -O2 part1.c; ./a.out input.txt

test1: part1.c
	gcc -g -O0 part1.c; ./a.out test-input.txt

part2: part2.c
	gcc -g part2.c; ./a.out input.txt

test2: part2.c
	gcc -g part2.c; ./a.out test-input.txt
