
part1: part1.c
	gcc part1.c; ./a.out hxbxwxba

test1: part1.c
	# gcc part1.c; ./a.out hijklmmn
	# gcc part1.c; ./a.out abbceffg
	# gcc part1.c; ./a.out abbcdgjk
	# gcc part1.c; ./a.out abcdefgh
	gcc part1.c; ./a.out ghijklmn

part2: part2.c
	gcc part2.c; ./a.out hxbxxyzz

test2: part2.c
	gcc part2.c; ./a.out 1 5
