
part1: part1.c
	gcc -g -O0 part1.c; cat input.txt | ./a.out

test1: part1.c
	gcc -g -O0 part1.c; cat test-input.txt | ./a.out

part2: part2.c
	gcc -g -O0 part2.c; cat input.txt | ./a.out

test2: part2.c
	gcc -g -O0 part2.c; cat test-input.txt | ./a.out
