part1: part1.c
	gcc -O2 part1.c; ./a.out 150 input.txt

test1: part1.c
	gcc -g part1.c; ./a.out 25 test-input.txt

part2: part2.c
	gcc -O2 part2.c; ./a.out 150 input.txt

test2: part2.c
	gcc -g part2.c; ./a.out 25 test-input.txt
